#include "oled_ctrl.h"

void 
oled_init()
{
    //TODO:
	
    //INIT CLOCK AND SET PRESCALER TO 8
	TCCR1B = CS11; 

    //MAX VAL TO COUNT TO IS 10,240 = 1/60
	TCNT1 = TIMER_VAL;
	
    //ENBALE INTERRUPT ON MATCH/OVERFLOW
    TIMSK = OCIE1B;

    //ENABLE GLOBAL INTERRUPT
    sei();
}

//TODO:
//IMPLEMENT INTERRUPT
//BASIC ISR - LEAVE FOR LATER
//MAKE NOTES WHAT TO ADD
ISR(OCF1B){
	
}